//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcClientProject.CalcServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalcService.DivisionResult", Namespace="http://schemas.datacontract.org/2004/07/CalcService")]
    [System.SerializableAttribute()]
    public partial class CalcServiceDivisionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quotientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int restField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quotient {
            get {
                return this.quotientField;
            }
            set {
                if ((this.quotientField.Equals(value) != true)) {
                    this.quotientField = value;
                    this.RaisePropertyChanged("quotient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rest {
            get {
                return this.restField;
            }
            set {
                if ((this.restField.Equals(value) != true)) {
                    this.restField = value;
                    this.RaisePropertyChanged("rest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcServiceReference.ICalcService")]
    public interface ICalcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/DoWork", ReplyAction="http://tempuri.org/ICalcService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/DoWork", ReplyAction="http://tempuri.org/ICalcService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/getDivisionResult", ReplyAction="http://tempuri.org/ICalcService/getDivisionResultResponse")]
        CalcClientProject.CalcServiceReference.CalcServiceDivisionResult getDivisionResult(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/getDivisionResult", ReplyAction="http://tempuri.org/ICalcService/getDivisionResultResponse")]
        System.Threading.Tasks.Task<CalcClientProject.CalcServiceReference.CalcServiceDivisionResult> getDivisionResultAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcServiceChannel : CalcClientProject.CalcServiceReference.ICalcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcServiceClient : System.ServiceModel.ClientBase<CalcClientProject.CalcServiceReference.ICalcService>, CalcClientProject.CalcServiceReference.ICalcService {
        
        public CalcServiceClient() {
        }
        
        public CalcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public CalcClientProject.CalcServiceReference.CalcServiceDivisionResult getDivisionResult(int a, int b) {
            return base.Channel.getDivisionResult(a, b);
        }
        
        public System.Threading.Tasks.Task<CalcClientProject.CalcServiceReference.CalcServiceDivisionResult> getDivisionResultAsync(int a, int b) {
            return base.Channel.getDivisionResultAsync(a, b);
        }
    }
}
