//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuctionItem", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class AuctionItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BidCustomNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BidCustomPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BidPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BidTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BidCustomName {
            get {
                return this.BidCustomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BidCustomNameField, value) != true)) {
                    this.BidCustomNameField = value;
                    this.RaisePropertyChanged("BidCustomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BidCustomPhone {
            get {
                return this.BidCustomPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.BidCustomPhoneField, value) != true)) {
                    this.BidCustomPhoneField = value;
                    this.RaisePropertyChanged("BidCustomPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BidPrice {
            get {
                return this.BidPriceField;
            }
            set {
                if ((this.BidPriceField.Equals(value) != true)) {
                    this.BidPriceField = value;
                    this.RaisePropertyChanged("BidPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BidTimeStamp {
            get {
                return this.BidTimeStampField;
            }
            set {
                if ((this.BidTimeStampField.Equals(value) != true)) {
                    this.BidTimeStampField = value;
                    this.RaisePropertyChanged("BidTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription {
            get {
                return this.ItemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionField, value) != true)) {
                    this.ItemDescriptionField = value;
                    this.RaisePropertyChanged("ItemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((this.ItemNumberField.Equals(value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RatingPrice {
            get {
                return this.RatingPriceField;
            }
            set {
                if ((this.RatingPriceField.Equals(value) != true)) {
                    this.RatingPriceField = value;
                    this.RaisePropertyChanged("RatingPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bid", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Bid : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        private string i;
        private string p;
        private string phone;
        private string name;

        public Bid(string i, string p, string phone, string name)
        {
            this.i = i;
            this.p = p;
            this.phone = phone;
            this.name = name;
        }

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomName {
            get {
                return this.CustomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNameField, value) != true)) {
                    this.CustomNameField = value;
                    this.RaisePropertyChanged("CustomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomPhone {
            get {
                return this.CustomPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomPhoneField, value) != true)) {
                    this.CustomPhoneField = value;
                    this.RaisePropertyChanged("CustomPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((this.ItemNumberField.Equals(value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAuctionService")]
    public interface IAuctionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/StartServer", ReplyAction="http://tempuri.org/IAuctionService/StartServerResponse")]
        void StartServer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/StartServer", ReplyAction="http://tempuri.org/IAuctionService/StartServerResponse")]
        System.Threading.Tasks.Task StartServerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/AllItems", ReplyAction="http://tempuri.org/IAuctionService/AllItemsResponse")]
        Client.ServiceReference1.AuctionItem[] AllItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/AllItems", ReplyAction="http://tempuri.org/IAuctionService/AllItemsResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.AuctionItem[]> AllItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/ReadItem", ReplyAction="http://tempuri.org/IAuctionService/ReadItemResponse")]
        Client.ServiceReference1.AuctionItem ReadItem(int itemNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/ReadItem", ReplyAction="http://tempuri.org/IAuctionService/ReadItemResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.AuctionItem> ReadItemAsync(int itemNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/Bid", ReplyAction="http://tempuri.org/IAuctionService/BidResponse")]
        string Bid([System.ServiceModel.MessageParameterAttribute(Name="bid")] Client.ServiceReference1.Bid bid1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/Bid", ReplyAction="http://tempuri.org/IAuctionService/BidResponse")]
        System.Threading.Tasks.Task<string> BidAsync(Client.ServiceReference1.Bid bid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuctionServiceChannel : Client.ServiceReference1.IAuctionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuctionServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.IAuctionService>, Client.ServiceReference1.IAuctionService {
        
        public AuctionServiceClient() {
        }
        
        public AuctionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuctionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuctionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuctionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartServer() {
            base.Channel.StartServer();
        }
        
        public System.Threading.Tasks.Task StartServerAsync() {
            return base.Channel.StartServerAsync();
        }
        
        public Client.ServiceReference1.AuctionItem[] AllItems() {
            return base.Channel.AllItems();
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.AuctionItem[]> AllItemsAsync() {
            return base.Channel.AllItemsAsync();
        }
        
        public Client.ServiceReference1.AuctionItem ReadItem(int itemNumber) {
            return base.Channel.ReadItem(itemNumber);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.AuctionItem> ReadItemAsync(int itemNumber) {
            return base.Channel.ReadItemAsync(itemNumber);
        }
        
        public string Bid(Client.ServiceReference1.Bid bid1) {
            return base.Channel.Bid(bid1);
        }
        
        public System.Threading.Tasks.Task<string> BidAsync(Client.ServiceReference1.Bid bid) {
            return base.Channel.BidAsync(bid);
        }
    }
}
